document.addEventListener("DOMContentLoaded", () => {
    const menuToggle = document.getElementById("menu-toggle");
    const sidebar = document.getElementById("sidebar");
    const countryButtons = document.querySelectorAll(".country-btn");
    const countryInfo = document.getElementById("country-info");

   
    const countryData = {
        poland: {
            name: "Polska",
            info: "Polska, oficjalnie Rzeczpospolita Polska, jest krajem w Europie Środkowej. Polska, oficjalnie Rzeczpospolita Polska, leży w Europie Środkowej. Zajmuje obszar o powierzchni około 312 696 km² i graniczy z Niemcami, Czechami, Słowacją, Ukrainą, Białorusią, Litwą oraz z Rosją przez Obwód Kaliningradzki. Ma dostęp do Bałtyku na północy. Krajobraz Polski jest zróżnicowany. Na południu kraju znajdują się góry, głównie Karpaty i Sudety, z najwyższym szczytem Rysy (2499 m n.p.m.). Centralna i północna Polska to tereny przeważnie płaskie, z obszarami nizin i wzgórz. Najdłuższą rzeką jest Wisła, przepływająca przez kraje centralne, w tym przez stolicę Warszawę. Inne ważne rzeki to Odra, Warta, Bug i Narew. Jeziora są szczególnie liczne w północno-wschodniej części kraju, w regionie mazurskim. Klimat Polski to umiarkowany klimat przejściowy między morskim a kontynentalnym, z chłodnymi zimami i umiarkowanie ciepłymi latami. Górzyste tereny w południowej Polsce doświadczają surowszych zim i chłodniejszych lat niż obszary nizinne.Polska ma bogate zasoby naturalne, w tym węgiel kamienny, rudy żelaza, miedzi, sól, gaz ziemny, ropa naftowa i torf, które odgrywały ważną rolę w rozwoju gospodarczym kraju. Dzięki swojej różnorodności geograficznej i historii Polska jest fascynującym miejscem do zwiedzania oraz istotnym graczem na arenie międzynarodowej. ",
            image: "https://ocdn.eu/pulscms-transforms/1/y23k9kuTURBXy80MjQ0ZTM4My1hZGU5LTQwMzItODgxMS1kYmIwNmE1N2NmOWEuanBlZ5GVAs0CZwDDw94AAaEwAQ"
        },
        germany: {
            name: "Niemcy",
            info: "Niemcy, oficjalnie Republika Federalna Niemiec, są krajem w Europie Zachodniej. Niemcy, oficjalnie Republika Federalna Niemiec, leżą w Europie Zachodniej. Zajmują obszar o powierzchni około 357 022 km² i graniczą z Daniią, Polską, Czechami, Austrią, Szwajcarią, Francją, Luksemburgiem, Belgią oraz Holandią. Krajobraz Niemiec jest zróżnicowany. Na południu kraju dominują góry, w tym Alpy Bawarskie, z najwyższym szczytem Zugspitze (2962 m n.p.m.). Północne Niemcy charakteryzują się przeważnie nizinami i pagórkami. Najważniejszą rzeką jest Ren, który przepływa przez zachodnie Niemcy. Inne ważne rzeki to Łaba, Odra, Menzura i Wezera. Niemcy posiadają także liczne jeziora, zwłaszcza w regionie południowej i północno-wschodniej. Klimat Niemiec jest umiarkowany, zróżnicowany w zależności od regionu. Wschodnie Niemcy mają kontynentalny klimat z bardziej surowymi zimami, podczas gdy zachodnie części kraju są bardziej wpływane przez klimat morski. Niemcy są jednym z największych gospodarczo krajów na świecie. Mają bogate zasoby naturalne, w tym węgiel brunatny, rudy żelaza, ruda miedzi, ropa naftowa i gaz ziemny, jednak większość surowców jest importowana. Niemcy są znane z wysokiego poziomu technologii, przemysłu samochodowego, maszynowego, chemicznego oraz turystyki. Dzięki swojej potędze gospodarczej i roli politycznej Niemcy są istotnym graczem na arenie międzynarodowej oraz popularnym celem podróży turystycznych.",
            image: "https://ocdn.eu/pulscms-transforms/1/SNlk9kuTURBXy84ZGVlMzA4My1jZmY1LTRkYjQtYjYwNi1jZWE3NTM4MmM3ODAuanBlZ5GVAs0CZwDDw94AAaEwAQ"
        },
        france: {
            name: "Francja",
            info: "Francja, oficjalnie Republika Francuska, jest krajem w Europie Zachodniej. Francja, oficjalnie Republika Francuska, leży w Europie Zachodniej. Zajmuje obszar o powierzchni około 551 695 km² i graniczy z Belgią, Luksemburgiem, Niemcami, Szwajcarią, Włochami, Monako, Hiszpanią i Andorą. Krajobraz Francji jest zróżnicowany. Na południu kraju znajdują się Alpy, z najwyższym szczytem Mont Blanc (4810 m n.p.m.), natomiast na południowym zachodzie rozciągają się Pireneje. Centralna Francja charakteryzuje się przeważnie nizinami, a na północy znajdują się pagórki i równiny. Najważniejszą rzeką jest Sekwana, przepływająca przez północną Francję, a także Rodan i Loara. Francja posiada również liczne jeziora, zwłaszcza w regionach Alp i Jura oraz na zachodzie kraju. Klimat Francji jest zróżnicowany, z wpływami morskim na zachodzie i kontynentalnym na wschodzie. Południowa Francja ma klimat śródziemnomorski, z ciepłymi, suchymi latami i łagodnymi zimami. Francja jest jednym z największych gospodarczo krajów na świecie. Jest znana z rolnictwa, przemysłu, turystyki i kultury. Kraj ten ma bogatą historię i dziedzictwo kulturowe, obejmujące sztukę, literaturę, kuchnię i architekturę. Dzięki swojej potędze gospodarczej, znaczeniu kulturowemu oraz roli politycznej Francja jest istotnym graczem na arenie międzynarodowej oraz popularnym celem podróży turystycznych.",
            image: "https://www.ifrancja.fr/wp-content/uploads/2023/05/Panteon-iFrancja-5.jpg"
        },
        italy: {
            name: "Włochy",
            info: "Włochy, oficjalnie Republika Włoska, są krajem w Europie Południowej. Włochy, oficjalnie Republika Włoska, leżą w Europie Południowej. Zajmują obszar o powierzchni około 301 340 km² i graniczą z Francją, Szwajcarią, Austrią i Słowenią. Krajobraz Włoch jest zróżnicowany. Na północy kraju dominują Alpy, a na południu Apeniny, z najwyższym szczytem Mont Blanc (4810 m n.p.m.). Centralna Włochy charakteryzują się przeważnie wzgórzami i równinami, a na południu rozciągają się wybrzeża Morza Śródziemnego. Najważniejszą rzeką jest Pad, przepływająca przez północne Włochy, a także Tyber, który przepływa przez Rzym. Włochy mają również liczne jeziora, zwłaszcza w regionie północnych Włoch i wokół Włoskiego Wybrzeża. Klimat Włoch jest zróżnicowany, z wpływami morskim na wybrzeżach i kontynentalnym we wnętrzu kraju. Północne Włochy mają klimat umiarkowany, podczas gdy południowe Włochy doświadczają klimatu śródziemnomorskiego, z gorącymi, suchymi latami i łagodnymi, deszczowymi zimami. Włochy są znane z bogatej historii, kultury, sztuki i kuchni. Mają ważne dziedzictwo kulturowe, obejmujące wiele zabytków starożytnych, renesansowych i barokowych. Włochy są również jednym z najważniejszych ośrodków mody i designu na świecie. Dzięki swojemu dziedzictwu kulturowemu, pięknemu krajobrazowi oraz znaczeniu turystycznemu Włochy są popularnym celem podróży dla turystów z całego świata.",
            image: "https://img.redro.pl/plakaty/rzym-wlochy-flaga-niebo-wakacje-700-108028671.jpg"
        },
        belarus: {
            name: "Białoruś",
            info: "Białoruś, oficjalnie Republika Białorusi, jest krajem w Europie Wschodniej. Białoruś, oficjalnie Republika Białorusi, leży w Europie Wschodniej. Zajmuje obszar o powierzchni około 207 600 km² i graniczy z Rosją, Ukrainą, Polską, Łotwą i Litwą. Krajobraz Białorusi jest głównie płaski, z niewielkimi pagórkami i dolinami rzecznymi. Największym obszarem naturalnym są Polesie Białoruskie na południu kraju. Najważniejszą rzeką jest Dniepr, który przepływa przez środkową część kraju. Inne ważne rzeki to Berezyna, Soż i Niemen. Białoruś ma również liczne jeziora, zwłaszcza w regionie Polesia. Klimat Białorusi jest umiarkowany, z zimami chłodnymi i śnieżnymi oraz latami umiarkowanie ciepłymi. Opady są równomiernie rozłożone przez cały rok. Białoruś ma bogate zasoby naturalne, w tym torf, drzewa, ruda potasowa, ropa naftowa i gaz ziemny. Gospodarka kraju opiera się głównie na przemyśle ciężkim i rolnictwie. Mimo że Białoruś nie jest tak powszechnie znana jak niektóre inne kraje europejskie, posiada bogatą historię i kulturę, która sięga tysięcy lat wstecz. Dzięki swojemu strategicznemu położeniu i zasobom naturalnym Białoruś odgrywa istotną rolę na arenie międzynarodowej.",
            image: "https://galeria.bankier.pl/p/a/4/a37735b8515803-948-568-0-334-4056-2433.jpg"
        },
        belgium: {
            name: "Belgia",
            info: "Belgia, oficjalnie Królestwo Belgii, jest krajem w Europie Zachodniej. Belgia, oficjalnie Królestwo Belgii, leży w Europie Zachodniej. Zajmuje obszar o powierzchni około 30 689 km² i graniczy z Francją, Holandią, Niemcami i Luksemburgiem. Krajobraz Belgii jest głównie płaski, z niewielkimi wzgórzami na południu kraju. Najważniejszym obszarem naturalnym są Ardeny na południu. Najważniejszą rzeką jest Moza, która przepływa przez środkową część kraju. Belgia ma również liczne kanały i rzeki, które są ważne dla transportu i gospodarki kraju.Klimat Belgii jest umiarkowany, z chłodnymi zimami i umiarkowanie ciepłymi latami. Opady są równomiernie rozłożone przez cały rok. Belgia ma bogate zasoby naturalne, w tym węgiel kamienny, rudy żelaza, sól, ropa naftowa i gaz ziemny. Gospodarka kraju opiera się głównie na przemyśle, usługach i handlu. Belgia jest znana z bogatej historii, kultury i sztuki. Posiada wiele zabytków, w tym średniowieczne miasta, zamki i katedry. Jest również siedzibą wielu międzynarodowych instytucji, takich jak Unia Europejska i NATO. Dzięki swojemu strategicznemu położeniu i znaczeniu gospodarczemu Belgia odgrywa istotną rolę w Europie i na świecie.",
            image: "https://images.pb.pl/filtered/aa45fa87-b457-4311-bfd9-78f07365437c/24942ac7-8838-5dfe-922c-1db28807eefa.jpg"
        },
        denmark: {
            name: "Dania",
            info: "Dania, oficjalnie Królestwo Danii, jest krajem w Europie Północnej. Dania, oficjalnie Królestwo Danii, leży w Europie Północnej. Zajmuje obszar o powierzchni około 42 933 km² i składa się głównie z półwyspu Jutlandzkiego oraz licznych wysp, w tym Zelandii, Funen i Bornholmu. Krajobraz Danii jest głównie płaski, z niewielkimi wzgórzami na wschodzie kraju. Duńskie wybrzeże jest bardzo urozmaicone, z licznymi fiordami i zatokami. Najważniejszą rzeką jest Gudenå, która przepływa przez środkową część kraju. Dania ma również wiele jezior, zwłaszcza na wyspie Zelandii. Klimat Danii jest umiarkowany, z chłodnymi zimami i umiarkowanie ciepłymi latami. Opady są równomiernie rozłożone przez cały rok. Dania ma bogate zasoby naturalne, w tym węgiel brunatny, ropa naftowa, gaz ziemny, sole potasowe i sól. Gospodarka kraju opiera się głównie na przemyśle, rolnictwie, usługach i handlu. Dania jest znana z bogatej historii, kultury i dziedzictwa. Jest domem dla wielu zabytków średniowiecznych, zamków i muzeów. Dania jest również jednym z najbardziej rozwiniętych społecznie krajów na świecie, znana z wysokiego poziomu życia, opieki zdrowotnej i edukacji.",
            image: "https://media.istockphoto.com/id/1172208374/pl/zdj%C4%99cie/kopenhaga-nyhavn-panorama-miasta-t%C5%82umy-korzystaj%C4%85cych-s%C5%82oneczne-restauracje-bary-dania.jpg?s=612x612&w=0&k=20&c=xSkJmNI4l71s7ZPBgwFMVo4pJX_JeXc_XvbKgUx1I60="
        },
        finland: {
            name: "Finlandia",
            info: "Finlandia, oficjalnie Republika Finlandii, jest krajem w Europie Północnej. Finlandia, oficjalnie Republika Finlandii, leży w Europie Północnej. Zajmuje obszar o powierzchni około 338 424 km² i graniczy z Norwegią, Szwecją i Rosją. Krajobraz Finlandii jest głównie płaski, z dużą ilością jezior i lasów. Na północy kraju znajdują się liczne obszary tundry, a na południu rozciągają się pagórki i niziny. Najważniejszą rzeką jest Kemijoki, która przepływa przez północną część kraju. Finlandia ma również tysiące jezior, w tym największe, Saimaa. Klimat Finlandii jest umiarkowany, z zimnymi zimami i umiarkowanie ciepłymi latami. Opady są częstsze latem niż zimą. Finlandia ma bogate zasoby naturalne, w tym drzewa, ruda żelaza, miedź, cynę, cynk, złoto i srebro. Gospodarka kraju opiera się głównie na przemyśle drzewnym, metalurgicznym, technologicznym i usługach. Finlandia jest znana z bogatej historii, kultury i dziedzictwa. Jest domem dla wielu zabytków historycznych, saun, i unikatowego języka i kultury fińskiej oraz dla nowoczesnych osiągnięć w dziedzinie technologii.",
            image: "https://ocdn.eu/pulscms-transforms/1/ElPk9kuTURBXy8zMTNhZjQ1MS04NjI5LTQyM2ItYWM4ZC04MGViZWEzODZlMzcuanBlZ5GVAs0CZwDDw94AAaEwAQ"
        },
        norway: {
            name: "Norwegia",
            info: "Norwegia, oficjalnie Królestwo Norwegii, jest krajem w Europie Północnej. Norwegia, oficjalnie Królestwo Norwegii, leży w Europie Północnej. Zajmuje obszar o powierzchni około 385 207 km² i graniczy z Rosją, Finlandią i Szwecją. Krajobraz Norwegii jest zróżnicowany, obejmując góry, fiordy, wyspy i wybrzeża. Na zachodzie kraju dominują góry Skandynawii, z najwyższym szczytem Galdhøpiggen (2469 m n.p.m.). Na wschodzie rozciągają się szerokie doliny i niziny. Najważniejszymi rzekami są Glomma i Nidelva, które przepływają przez środkową i południową Norwegię. Norwegia ma również wiele jezior, głównie na południu i wschodzie kraju. Klimat Norwegii jest zróżnicowany, z chłodnymi zimami i umiarkowanie ciepłymi latami. Opady są częstsze na zachodnim wybrzeżu, gdzie wpływ ma ciepły prąd zatokowy. Norwegia ma bogate zasoby naturalne, w tym ropę naftową, gaz ziemny, ryby, węgiel brunatny, rudy żelaza, miedź, cynę, cynk i kwarc. Gospodarka kraju opiera się głównie na przemyśle wydobywczym, rybołówstwie, przemyśle drzewnym, turystyce i usługach. Norwegia jest znana z bogatej historii, kultury i dziedzictwa. Jest domem dla wielu zabytków historycznych, fjordów, wodospadów i pięknych krajobrazów. Norwegia jest również jednym z najbardziej rozwiniętych społecznie krajów na świecie, znana z wysokiego poziomu życia, opieki zdrowotnej i edukacji.",
            image: "https://www.national-geographic.pl/media/cache/big/uploads/media/default/0014/64/oslo.jpeg"
        },
        ukraine: {
            name: "Ukraina",
            info: "Ukraina, oficjalnie Republika Ukrainy, jest krajem w Europie Wschodniej. Ukraina, oficjalnie Republika Ukrainy, leży w Europie Wschodniej. Zajmuje obszar o powierzchni około 603 500 km² i graniczy z Białorusią, Rosją, Mołdawią, Węgrami, Słowacją, Polską i Rumunią. Krajobraz Ukrainy jest zróżnicowany, obejmując niziny, góry i stepy. Na zachodzie kraju dominują Karpaty, a na wschodzie rozciągają się niziny i stepy. Najważniejszymi rzekami są Dniepr, Don i Dniestr, które przepływają przez różne regiony Ukrainy. Ukraina ma również wiele jezior, zwłaszcza na północnym zachodzie kraju. Klimat Ukrainy jest umiarkowany, z chłodnymi zimami i umiarkowanie ciepłymi latami. Opady są różne w zależności od regionu, z większymi opadami na zachodzie i północy kraju. Ukraina ma bogate zasoby naturalne, w tym węgiel kamienny, rudy żelaza, miedź, ropa naftowa, gaz ziemny, sól, potas i sole kamienne. Gospodarka kraju opiera się głównie na przemyśle ciężkim, wydobyciu surowców naturalnych, rolnictwie i usługach. Ukraina ma bogatą historię, kulturę i dziedzictwo. Jest domem dla wielu zabytków historycznych, klasztorów, cerkwi i muzeów. Ukraina odgrywa istotną rolę na arenie międzynarodowej ze względu na swoje strategiczne położenie i bogate zasoby naturalne.",
            image: "https://bi.im-g.pl/im/5c/cf/1a/z28112988AMP,Flaga-Ukrainy-nad-Kijowem.jpg"
        },
        spain: {
            name: "Hiszpania",
            info: "Hiszpania, oficjalnie Królestwo Hiszpanii, jest krajem w Europie Południowej. Hiszpania, oficjalnie Królestwo Hiszpanii, leży w Europie Południowej. Zajmuje obszar o powierzchni około 505 990 km² i graniczy z Francją, Andorą, Portugalią, Wielką Brytanią (Gibraltar) oraz z Marokiem przez terytorium autonomiczne Ceuta i Melilla w północnej Afryce. Krajobraz Hiszpanii jest zróżnicowany, obejmując góry, równiny i wybrzeża. Na północy kraju dominują Góry Kantabryjskie i Pireneje, a na południu rozciągają się Góry Sierra Nevada i Góry Betyckie. Liczne wybrzeża Hiszpanii są popularnym celem turystycznym, zwłaszcza Costa del Sol i Costa Brava. Najważniejszymi rzekami są Tag, Duero, Ebro, Guadalquivir i Tajo, które przepływają przez różne regiony Hiszpanii. Kraj ten ma również wiele jezior, zwłaszcza w regionie północno-wschodniej Hiszpanii. Klimat Hiszpanii jest zróżnicowany, z klimatem śródziemnomorskim na wybrzeżach, klimatem oceanicznym na północy, kontynentalnym w środkowej części kraju oraz pustynnym na południu. Hiszpania ma średnio ponad 300 dni słońca w roku. Hiszpania ma bogate zasoby naturalne, w tym rudy żelaza, węgiel kamienny, rudy miedzi, ruda cynku, rudy ołowiu, antymon, ruda rtęci, ropa naftowa, gaz ziemny, sole potasowe, sól kamienne, fosforyty, gips, fluoryt, baryt, siarkę i chalcedon. Gospodarka kraju opiera się głównie na turystyce, przemyśle, rolnictwie i rybołówstwie. Hiszpania ma bogatą historię, kulturę i dziedzictwo. Jest domem dla wielu zabytków historycznych, zabytków średniowiecznych, renesansowych i barokowych, zabytków UNESCO oraz unikatowych tradycji i festiwali. Hiszpania jest również jednym z najważniejszych krajów na świecie pod względem turystyki, przemysłu filmowego i kulinariów.",
            image: "https://media.brate.com/images/europa/hiszpania/madryt/madryt-13.jpg"
        },
        portugal: {
            name: "Portugalia",
            info: "Portugalia, oficjalnie Republika Portugalska, jest krajem w Europie Południowej. Portugalia, oficjalnie Republika Portugalska, leży w Europie Południowej. Zajmuje obszar o powierzchni około 92 212 km² i graniczy z Hiszpanią na północy i na wschodzie oraz posiada wybrzeże atlantyckie na zachodzie i południu. Krajobraz Portugalii jest zróżnicowany, obejmując góry, równiny i wybrzeża. Na północy kraju dominują Góry Pirenejskie, a na południu rozciągają się Góry Algarve. Liczne plaże Portugalii są popularnym celem turystycznym, zwłaszcza w regionach Algarve i Costa da Caparica. Najważniejszymi rzekami są Tag, Duero, Mondego i Guadiana, które przepływają przez różne regiony Portugalii. Kraj ten ma również wiele jezior, zwłaszcza w regionie północnej Portugalii. Klimat Portugalii jest zróżnicowany, z klimatem śródziemnomorskim na wybrzeżach, klimatem oceanicznym na północy i kontynentalnym w środkowej części kraju. Portugalia ma średnio ponad 300 dni słońca w roku. Portugalia ma bogate zasoby naturalne, w tym rudy żelaza, węgiel kamienny, ropa naftowa, gaz ziemny, rudy miedzi, mangan, uran, miki, chalcedon, sól kamienną, fosforyty, gips, sole potasowe, granity i wapienie. Gospodarka kraju opiera się głównie na turystyce, przemyśle, rolnictwie i rybołówstwie. Portugalia ma bogatą historię, kulturę i dziedzictwo. Jest domem dla wielu zabytków historycznych, zabytków UNESCO, klasztorów, zamków, kościołów i muzeów. Portugalia jest również znana z wyśmienitej kuchni, win i festiwali.",
            image: "https://www.trade.gov.pl/wp-content/uploads/2023/11/189189269_m_normal_none.jpg"
        },
        netherlands: {
            name: "Holandia",
            info: "Holandia, oficjalnie Królestwo Niderlandów, jest krajem w Europie Zachodniej. Holandia, oficjalnie Królestwo Niderlandów, leży w Europie Zachodniej. Zajmuje obszar o powierzchni około 41 543 km² i graniczy z Niemcami na wschodzie, Belgią na południu oraz posiada dostęp do Morza Północnego na zachodzie i północy. Krajobraz Holandii jest głównie płaski, z niewielkimi wzgórzami na południu kraju. Charakterystyczne dla Holandii są liczne kanały i rzeki, a także obszary polderów, które zostały osuszone i zamienione na użytki rolne. Najważniejszymi rzekami są Ren, Moza i Skalda, które przepływają przez różne regiony Holandii. Kraj ten ma również wiele jezior, zwłaszcza na północnym wschodzie i zachodzie kraju. Klimat Holandii jest umiarkowany, z chłodnymi zimami i umiarkowanie ciepłymi latami. Opady są równomiernie rozłożone przez cały rok. Holandia ma bogate zasoby naturalne, w tym gaz ziemny, sól kamienną, węgiel brunatny, ropa naftowa, gaz ziemny i wapień. Gospodarka kraju opiera się głównie na handlu, przemyśle, usługach, turystyce i rolnictwie. Holandia jest znana z bogatej historii, kultury i dziedzictwa. Jest domem dla wielu zabytków historycznych, muzeów, malowniczych miast i unikatowej architektury, w tym charakterystycznych wiatraków i kanałów. Holandia jest również znana z innowacji, tolerancji i wysokiego standardu życia.",
            image: "https://media.brate.com/images/europa/holandia/holandia.jpeg"
        }
    };


    menuToggle.addEventListener("click", () => {
        sidebar.classList.toggle("show-sidebar");
        menuToggle.classList.toggle("show-sidebar");
    });

    
    countryButtons.forEach(button => {
        button.addEventListener("click", () => {
            const countryKey = button.getAttribute("data-country");
            const country = countryData[countryKey];
            
            if (country) {
                countryInfo.innerHTML = `
                    <div class="country-info-content">
                        <h2>${country.name}</h2>
                        <p>${country.info}</p>
                    </div>
                `;
                countryInfo.style.backgroundImage = `url(${country.image})`;
            }
        });
    });
});
